/* This is an account selection dialog that is displayed after login if the user has multiple accounts (debit/credit). It:
- receives information from the login
- displays the user's name
- displays only the buttons (Debit/Credit) that the user actually has
- opens the actual account window based on the selection
- draws the background image manually */ 

#include "accountselect.h"
#include "account.h"
#include "adminwindow.h"
#include "ui_accountselect.h"
#include <QPainter>
#include <QPixmap>

// accountselect is a modal dialog shown after login, allowing the user to choose between Debit and Credit accounts
accountselect::accountselect(
    const LoginResultDto& loginResult,  // Data returned from successful login
    ApiClient* api,                     // API client (shared with other windows)
    QWidget *parent
)
: QDialog(parent)
, ui(new Ui::accountselect)
, m_api(api)
, m_login(loginResult)
{
    // Initialize UI elements generated by Qt Designer
    ui->setupUi(this);
    
    // Display the logged-in user's identifier
    ui->labelTest->setText("Käyttäjä: " + m_login.fName);
    
    // Build a map from account type ("debit"/"credit") to account ID
    for (const AccountDto& acc : m_login.accounts) {
        accountIdByType[acc.type.toLower()] = acc.idAccount;
    }
    
    // Check which account types the user has
    const bool hasDebit  = accountIdByType.contains("debit");
    const bool hasCredit = accountIdByType.contains("credit");
    QString hasAdmin = loginResult.role;
    
    // Show only the buttons that correspond to existing accounts
    ui->btnSelectDebit->setVisible(hasDebit);
    ui->btnSelectCredit->setVisible(hasCredit);

}

// Destructor: clean up UI
accountselect::~accountselect()
{
    delete ui;
}

// Called automatically when the Debit button is clicked
void accountselect::on_btnSelectDebit_clicked()
{
    selectedAccountType = "debit";
    openAccountWindow();
}

// Called automatically when the Credit button is clicked
void accountselect::on_btnSelectCredit_clicked()
{
    selectedAccountType = "credit";
    openAccountWindow();
}

// Called automatically when the Admin button is clicked
// void accountselect::on_btnSelectAdmin_clicked()
// {
//     openAdminWindow();
// }

// Opens the main account window based on the selected account type
void accountselect::openAccountWindow()
{
    // Resolve account ID from the selected type
    const int idAccount = accountIdByType.value(selectedAccountType, -1);
    if (idAccount < 0) return;

    // Create the account window
    account* accountWindow = new account(
        idAccount,
        m_login.idUser,
        m_login.fName,
        m_api,
        nullptr
    );
    
    // Automatically delete the window object when it is closed
    accountWindow->setAttribute(Qt::WA_DeleteOnClose);
    // Show the account window in full screen
    accountWindow->showMaximized();
    // Close this account selection dialog
    close();
}

// Custom paint event to draw a background image for the dialog
void accountselect::paintEvent(QPaintEvent *)
{
    QPainter painter(this);
    // Load background image from Qt resource system
    QPixmap bg(":/images/background.png");
    // Scale and draw the image to fill the entire dialog
    painter.drawPixmap(rect(), bg);
}



