/* This is the header for the accountselect class. It defines:
- what data the dialog receives after login
- what signal-slot methods the UI uses
- what internal state the class maintains
- what methods it overrides from Qt (paintEvent) */

#ifndef ACCOUNTSELECT_H
// Include guard: prevents multiple inclusion of this header
#define ACCOUNTSELECT_H

#include "account.h"
#include "adminwindow.h"
#include <QDialog>
#include <QMap>

#include "apiclient.h"

// Forward declaration of the UI class generated by Qt Designer
namespace Ui {
class accountselect;
}

// accountselect is a dialog shown after login that allows the user to choose which account (debit or credit) to use
class accountselect : public QDialog
{
    Q_OBJECT
    
    public:
    // Constructor
    // - loginResult: data returned from a successful login
    // - api: shared API client used for backend communication
    // - parent: optional parent widget
    explicit accountselect(
        const LoginResultDto& loginResult,
        ApiClient* api,
        QWidget *parent = nullptr
    );
    // Destructor
    ~accountselect();
    
    protected:
    // Overridden paint event to allow custom background drawing
    void paintEvent(QPaintEvent *event) override;
    
    private slots:
    // Slot called when the Debit button is clicked
    void on_btnSelectDebit_clicked();
    // Slot called when the Credit button is clicked
    void on_btnSelectCredit_clicked();
    
    void on_btnSelectAdmin_clicked();

private:
    // Pointer to the UI elements generated from accountselect.ui
    Ui::accountselect *ui;
    
    // Shared API client (not owned by this dialog)
    ApiClient* m_api;
    // Login data containing user info and available accounts
    LoginResultDto m_login;
    
    // Currently selected account type ("debit" or "credit")
    QString selectedAccountType;
    // Maps account type strings ("debit", "credit") to account IDs
    QMap<QString, int> accountIdByType;
    
    // Opens the main account window for the selected account
    void openAccountWindow();
    void openAdminWindow();
};

#endif // ACCOUNTSELECT_H
