/* This is the header for the MainWindow class. It defines:
- which Qt class is inherited
- which slots the window provides
- what internal space the login and splash logic needs
- which methods are overridden from Qt */

#ifndef MAINWINDOW_H
// Include guard: prevents multiple inclusion of this header
#define MAINWINDOW_H

#include "accountselect.h"
#include <QMainWindow>
#include <QTimer>
#include <QAction>

#include "adminwindow.h"
#include "apiclient.h"

// Forward declaration of the UI class generated by Qt Designer
QT_BEGIN_NAMESPACE
namespace Ui {
class MainWindow;
}
QT_END_NAMESPACE

// MainWindow is the application's main entry window
// It shows a splash screen, then a login form, handles authentication and transitions to the account selection dialog after successful login
class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    // Constructor / destructor
    explicit MainWindow(QWidget *parent = nullptr);
    ~MainWindow();

protected:
    // Overridden paint event to draw custom background images
    void paintEvent(QPaintEvent *event) override;

private slots:
    // Called when the splash screen timer expires
    void showMainScreen();
    // Called when the login button is clicked or Enter is pressed
    void on_KirjauduButton_clicked();

private:
    // Action used to toggle password visibility in the PIN field
    QAction* togglePasswordAction = nullptr;
    // Tracks whether the password is currently visible
    bool passwordVisible = false;

    // Pointer to the UI elements generated from mainwindow.ui
    Ui::MainWindow *ui;

    // True while the splash screen is being displayed
    bool isSplashScreen;
    // Timer controlling the splash screen duration
    QTimer *splashTimer;

    // API client responsible for backend communication
    ApiClient* api = nullptr;
    // Account selection dialog shown after successful login
    accountselect* accountSelectWindow = nullptr;
    // Adminwindow if logged in as admin
    adminwindow* adminWindow = nullptr;

    // Shows or hides the login controls
    void setMainControlsVisible(bool visible);

};
#endif // MAINWINDOW_H
