/* This is the header for the MainWindow class. It defines:
- which Qt class is inherited
- which slots the window provides
- what internal space the login and splash logic needs
- which methods are overridden from Qt */

#ifndef MAINWINDOW_H
// Include guard: prevents multiple inclusion of this header
#define MAINWINDOW_H

#include "accountselect.h"
#include <QMainWindow>
#include <QTimer>
#include <QAction>
#include <QProcess>
#include <QCoreApplication>
#include <QEvent>

#include "adminwindow.h"
#include "apiclient.h"

// Forward declaration of the UI class generated by Qt Designer
QT_BEGIN_NAMESPACE
namespace Ui {
class MainWindow;
}
QT_END_NAMESPACE

// MainWindow is the application's main entry window
// It shows a splash screen, then a login form, handles authentication and transitions to the account selection dialog after successful login
class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    // Constructor / destructor
    explicit MainWindow(QWidget *parent = nullptr);
    ~MainWindow();
    
    protected:
    // Event filter used to detect user activity (keyboard/mouse) and reset inactivity timers
    bool eventFilter(QObject* obj, QEvent* event) override;
    // Overridden paint event to draw custom background images
    void paintEvent(QPaintEvent *event) override;

private slots:
    // Called when the splash screen timer expires
    void showMainScreen();
    // Called when the login button is clicked or Enter is pressed
    void on_KirjauduButton_clicked();
    
    private:
    // Global inactivity timer (e.g. 30s idle -> return to initial state)
    QTimer* inactivityTimer = nullptr;

    // Resets the global inactivity timer whenever user activity is detected
    void resetInactivityTimer();
    // Returns the UI to the initial state (e.g. clears fields, shows splash/login as needed)
    void returnToInitialState();

    // PIN entry inactivity timer (e.g. 10s idle while entering PIN -> reset/clear PIN)
    QTimer* pinTimeoutTimer = nullptr;

    // Arms or resets the PIN timeout timer (called on input activity in the PIN field)
    void armOrResetPinTimeout();
    // Restarts the entire application process (hard reset)
    void restartApplication();
    // Action used to toggle password visibility in the PIN field
    QAction* togglePasswordAction = nullptr;
    // Tracks whether the password is currently visible
    bool passwordVisible = false;

    // Pointer to the UI elements generated from mainwindow.ui
    Ui::MainWindow *ui = nullptr;
    
    // True while the splash screen is being displayed
    bool isSplashScreen = true;
    // Timer controlling the splash screen duration
    QTimer *splashTimer = nullptr;
    
    // API client responsible for backend communication
    ApiClient* api = nullptr;
    // Account selection dialog shown after successful login
    accountselect* accountSelectWindow = nullptr;
    // Adminwindow if logged in as admin
    adminwindow* adminWindow = nullptr;

    // Shows or hides the login controls
    void setMainControlsVisible(bool visible);

};
#endif // MAINWINDOW_H
